### ISSUE TITLE
nice!

### ISSUE THREAD

**Issue by aquynh** [hunter-ht-2018/ptfuzzer#1]
this sounds like a very cool project, congrats! is there any paper accompanying?

keep it up, cheers!

**Comment by zhanggenex** [comment]
Thanks for your nice concern, our hunter group will keep going.
And the paper about PTfuzzer is under writing and will be finished soon.

**Comment by zhanggenex** [comment]
Thanks for your nice concern, our hunter group will keep going.
And the paper about PTfuzzer is under writing and will be finished soon.
