### ISSUE TITLE
No instrumentation detected

### ISSUE THREAD

**Issue by agarciagonzalez** [hunter-ht-2018/ptfuzzer#10]
Hello

There is hardly any documentation and I do not know what I am doing wrong. 
ptfuzzer.py error:
...
afl-fuzz 2.52b by <lcamtuf@google.com>
raw_bin: .testbin.text
min_addr: 93824991235680
max_addr: 93824991265601
entry_point: 93824992244510
init pt fuzzer.
start to disassmble binary...
build_cofi_map, total number of cofi instructions: 1050
cofi map complete percentage: 100%
[+] You have 12 CPU cores and 1 runnable tasks (utilization: 8%).
[+] Try parallel jobs - see docs/parallel_fuzzing.txt.
[*] Checking CPU core loadout...
[+] Found a free CPU core, binding to #0.
[*] Checking core_pattern...
[*] Checking CPU scaling governor...
[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Scanning '/tmp/ptfuzzer/inputs'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Validating target binary...
[*] Attempting dry run with 'id:000000,orig:ls'...
BRANCH_MODE is null, using default TNT mode.
Run ptfuzzer with TNT_MODE

[-] PROGRAM ABORT : No instrumentation detected
         Location : perform_dry_run(), /home/devel/ptfuzzer/afl-pt/afl-ptfuzz.c:2943

My cpu supports Intel PT and tested using perf record -e intel_pt// /bin/ls

Version: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz

Please help

**Comment by zhanggenex** [comment]
@agarciagonzalez 
try **config-run.sh**

**Comment by zhanggenex** [comment]
@agarciagonzalez 
currently PTfuzzer dose not support parrallel fuzzing because of the filter mechanism (several MSR registers)
