### ISSUE TITLE
open PT event failed

### ISSUE THREAD

**Issue by mudongliang** [hunter-ht-2018/ptfuzzer#16]
![Screenshot from 2019-04-22 10-59-45](https://user-images.githubusercontent.com/6214861/56506899-ca906c00-64ed-11e9-8adf-edbc79e05ef4.png)
ERROR: : Invalid argument
mmap(mmapAuxBuf) failed, try increasing the kernel.perf_event_mlock_kb sysctl (up to even 300000000)
open PT event failed.

The hardware configuration is as follows:
**CPU**:Intel(R) Core(TM) i5-7260U CPU @ 2.20GHz
**Memory**: 8G

**Comment by zhanggenex** [comment]
You might config PERF_AUX_BUFFER_SIZE to a bigger value
