### ISSUE TITLE
Does ptfuzzer support ForkServer?

### ISSUE THREAD

**Issue by mudongliang** [hunter-ht-2018/ptfuzzer#17]
Forkserver is an optimization method in AFL. From the following code,

```C
  if (!getenv("AFL_NO_FORKSRV"))    no_forkserver    = 1;
```

I infer that developers disable forkserver by default. So I wonder whether ptfuzzer supports forkserver.

**Comment by zhanggenex** [comment]
forkserver is disabled in ptfuzzer
