### ISSUE TITLE
Why does a single instance of ptfuzz need to setup IP Address Filtering on all available cores?

### ISSUE THREAD

**Issue by passthecilantro** [hunter-ht-2018/ptfuzzer#21]
Hi, 
I wanted to run multiple instances of ptfuzz at the same time using different target applications however I discovered from [here ](https://github.com/hunter-ht-2018/ptfuzzer/issues/4#issuecomment-403806519)that ptfuzz does not support more than one fuzzing task.  Then I noticed that in [afl-ptfuzz.c](https://github.com/hunter-ht-2018/ptfuzzer/blob/631b5222ea38917e71a14dc8f77b71787e928753/afl-pt/afl-ptfuzz.c#L8163) that a single fuzzing instance sets up the IP Address Filtering by writing the base and max address to msr 0x581 and 0x580 for **all cores**. 
Is there a reason why this needs to be done to have ptfuzz  work? 
Is there a way potential way for ptfuzz in the future support multiple fuzzing instances? 
What if you supported pinning a ptfuzz instance to a single logical core (like how AFL does it with the -b option) and then only configured the IP Address Filtering to that specific logical core's MSRs, is this possible for ptfuzz?

**Comment by zhanggenex** [comment]
> Is there a reason why this needs to be done to have ptfuzz work?
Its because of IP filtering PTFuzz. Without IP filtering, the decoder cannot run correctly.
> Is there a way potential way for ptfuzz in the future support multiple fuzzing instances?
You could google following fuzzers using PT, they did multiple fuzzing.
